volumes:
  caddy_data:
  caddy_config:
include:
  - service/http.docker-compose.yaml
  - service/ui.docker-compose.yaml
services:
  caddy:
    image: "caddy:2.9"
    depends_on:
      - caddy-atlas
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - ${ROOT_NS}0000:443
      - ${ROOT_NS}2000:80
      - ${ROOT_NS}3000:443
    volumes:
      - $PWD/conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
  caddy-atlas:
      image: $ROOT_IMAGE
      entrypoint: launcher
      command: pnpm exec nx run-many -t atlas:caddy
      environment: 
        LOG_LEVEL: $LOG_LEVEL
        STRUCTURED_LOGGING: $STRUCTURED_LOGGING
        ATLAS_CADDYFILE: /conf/Caddyfile
        MAGMAP_HTTP: $MAGMAP_HTTP
        MAGMAP_UI: $MAGMAP_UI
      volumes: 
        - $PWD/../conf:/conf

