volumes:
  caddy_data:
  caddy_config:
include:
  - service/http.docker-compose.yaml
  - service/ui.docker-compose.yaml
services:
  caddy:
    image: "caddy:2.9"
    depends_on:
      - atlas
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - ${ROOT_NS}0000:443
      - ${ROOT_NS}2000:80
      - ${ROOT_NS}3000:443
    volumes:
      - $PWD/conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
  atlas:
      image: $ROOT_IMAGE
      entrypoint: launcher
      command: iac/images/compose/$COMPOSE_PROJECT_NAME/service/atlas.mts
      environment: 
        LOG_LEVEL: $LOG_LEVEL
        ATLAS_CADDYFILE: /conf/Caddyfile
      volumes: 
        - $PWD/../conf:/conf
        - $PWD:/service

