services:
  nginx:
    image: "nginx:1.27"
    ports:
      - "3200:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
  spork-manifest-ui:
    image: spork
    entrypoint: project
    environment:
      PROJECT_PATH: ./packages/manifest-ui
      PROJECT_COMMAND: staticwww:dev
      PORT: "3201"
    ports:
      - "3201:3201"
    volumes:
      # iac/images/compose/manifest
      - "../../../..:/workspace"
  spork-http:
    image: spork
    entrypoint: project
    environment:
      PROJECT_PATH: .
      PROJECT_COMMAND: http:start
      PORT: "3202"
    ports:
      - "3202:3202"
    volumes:
      # iac/images/compose/manifest
      - "../../../..:/workspace"
  # spork-manifest-io:
  #   image: spork
  #   entrypoint: project
  #   environment:
  #     PROJECT_PATH: ./packages/manifest-io
  #     PROJECT_COMMAND: dev:staticwww
  #     PORT: "3201"
  #   ports:
  #     - "3201:3201"
  # postgres:
  #   image: "postgres:17"