packages:
  - '.'
  - 'canary'
  - 'examples/*'
  - 'iac/*'
  - 'packages/*'
  - 'protocols/*'
catalog:
  "@levicape/paloma": "0.2.0-main.6"
  "@levicape/fourtwo": "0.7.1-main.15"
  "@levicape/fourtwo-pulumi": "0.7.1-main.15"
  "@levicape/fourtwo-builders": "0.7.1-main.15"





  











catalogs:
  aws:
    "@aws/codecatalyst-workflows-sdk": "^0.1.5-preview.6"
    "@aws-sdk/client-dynamodb": "^3.731.0"
    "@aws-sdk/client-secrets-manager": "^3.731.0"
    "@aws-sdk/client-sqs": "^3.731.0"
    "@aws-sdk/lib-dynamodb": "^3.731.0"
    "@aws-sdk/util-dynamodb": "^3.731.0"
    "aws-lambda-ric": "^3.2.1"
    "aws4fetch": "^1.0.20"
    "pino-lambda": "^4.4.1"
  build:
    "esbuild": "^0.24.2"
    "folder-hash": "^4.0.4"
    "nexe": "4.0.0-rc.6"
    "node-gyp": "^11.0.0"
  cli:
    "@stricli/core": "^1.1.1"
    "enquirer": "^2.4.1"
  compression:
    "archiver": "^7.0.1"
  core:
    "fast-xml-parser": "^4.5.0"
    "ini": "^5.0.0"
    "jsonc-parser": "^3.3.1"
    "js-yaml": "^4.1.0"
    "long": "^5.2.3"
    "pify": "^6.1.0"
    "pretty-ms": "^9.2.0"
    "std-env": "^3.8.0"
    "yaml": "^2.7.0"
    "zod": "^3.24.1"
  crypto:
    "bcryptjs": "^2.4.3"
    "crypto-js": "^4.2.0"
    "crypto.js": "^3.2.2"
    "jsonwebtoken": "^9.0.2"
  database-postgres:
    "pg": "^8.13.1"
  database-sql:
    "db0": "^0.2.3"
    "knex": "^3.1.0"
    "slonik": "^46.4.0"
  database-sqlite:
    "better-sqlite3": "^11.8.1"
  dev:
    "typescript": "^5.7.3"
    "tsx": "^4.19.2"
  effect:
    "effect": "^3.12.7"
    "@effect/platform": "^0.75.1"
    "@effect/platform-node": "^0.71.1"
  error:
    "serialize-error": "^12.0.0"
    "verror": "^1.10.0"
  http:
    "cookie": "^1.0.2"
    "cookie-signature": "^1.2.2"
    "http-status-codes": "^2.3.0"
    "isbot": "^5.1.21"
    "odata-filter-parser": "^0.5.5"
  http-express:
    "express": "^4.21.2"
    "sirv": "^3.0.0"
  hono:
    "@hono/node-server": "^1.13.7"
    "@hono/zod-validator": "^0.4.2"
    "compressible": "^2.0.18"
    "hono": "^4.6.16"
    "hono-rate-limiter": "^0.4.2"
  id:
    "@paralleldrive/cuid2": "^2.2.2"
    "ksuid": "^3.0.0"
    "nanoid": "^5.0.9"
    "slugid": "^5.0.1"
    "uuid-base64-ts": "^1.0.2"
    "ulidx": "^2.4.1"
  kubernetes:
    "@kubernetes-models/postgres-operator": "^0.4.2"
  lint:
    "@biomejs/biome": "^1.9.4"
  log-awspowertools:
    "@aws-lambda-powertools/logger": "^2.13.1"
  log-consola:
    "consola": "^3.4.0"
  log-loglayer:
    "@loglayer/transport-aws-lambda-powertools": "^2.0.6"
    "@loglayer/transport-consola": "^1.0.14"
    "loglayer": "^5.5.1"
  package:
    "ci": "^2.3.0"
    "depcheck": "^1.4.7"
    "publint": "^0.3.2"
    "syncpack": "^13.0.1"
  parse-json:
    "destr": "^2.0.3"
  parse-path:
    "pathe": "^2.0.2"
  project-nx:
    "nx": "^20.4.0"
  protobuf:
    "@bufbuild/protobuf": "^2.2.3"
    "@bufbuild/buf": "^1.44.0"
    "ts-proto": "^2.6.1"
  pulumi:
    "@pulumi/aws": "^6.67.0"
    "@pulumi/awsx": "^2.21.0"
    "@pulumi/aws-native": "^1.24.0"
    "@pulumi/command": "^1.0.1"
    "@pulumi/docker": "^4.5.7"
    "@pulumi/docker-build": "^0.0.9"
    "@pulumi/kubernetes": "^4.18.4"
    "@pulumi/pulumi": "^3.147.0"
    "@pulumi/random": "^4.16.7"
    "@pulumi/synced-folder": "^0.11.1"
    "@pulumiverse/time": "^0.1.0"
  server:
    "@stricjs/cluster": "^2.0.0"
    "@stricjs/utils": "^2.0.7"
    "chokidar": "^4.0.3"
    "hookable": "^5.5.3"
    "lru-cache": "^11.0.2"
    "node-html-parser": "^7.0.1"
    "unzipper": "^0.12.3"
  test:
    "expect": "^29.7.0"
  types:
    "@total-typescript/ts-reset": "^0.6.1"
    "@types/bcryptjs": "^2.4.6"
    "@types/better-sqlite3": "^7.6.12"
    "@types/compressible": "^2.0.2"
    "@types/cookie-signature": "^1.1.2"
    "@types/express": "^4.17"
    "@types/folder-hash": "^4.0.4"
    "@types/ini": "^4.1.1"
    "@types/js-yaml": "^4.0.9"
    "@types/jsonwebtoken": "^9.0.7"
    "@types/module-alias": "^2.0.4"
    "@types/node": "^22.13.1"
    "@types/qrcode": "^1.5.5"
    "@types/react": "^19.0.1"
    "@types/react-dom": "^19.0.1"
    "@types/unzipper": "^0.10.10"
    "@types/verror": "^1.10.10"
    "tslib": "^2.8.1"
  web:
    "@conform-to/zod": "^1.2.2"
    "@epic-web/cachified": "^5.2.0"
    "@epic-web/client-hints": "^1.3.5"
    "@epic-web/invariant": "^1.0.0"
    "@epic-web/remember": "^1.1.0"
    "@epic-web/totp": "^2.0.0"
    "redaxios": "^0.5.1"
    "spin-delay": "^2.0.1"
  web-build:
    "vinxi": "^0.5.1"
    "webpack": "^5.97.1"
  web-cloudscape:
    "@cloudscape-design/components": "^3.0.873"
    "@cloudscape-design/global-styles": "^1.0.34"
  web-dom:
    "input-otp": "^1.4.1"
    "qrcode": "^1.5.4"
    "sonner": "^1.7.0"
  web-polaris:
    "@shopify/polaris-icons": "^9.3.0"
  web-react:
    "@conform-to/react": "^1.2.2"
    "@uidotdev/usehooks": "^2.4.1"
    "ahooks": "^3.8.1"
    "react": "^19.0.0"
    "react-dom": "^19.0.0"
    "react-is": "^18.3.1"
    "react-keyed-flatten-children": "^3.0.2"
  web-react-router:
    "@react-router/dev": "^7.1.3"
    "@react-router/node": "^7.1.3"
    "@react-router/serve": "^7.1.3"
    "@react-router/fs-routes": "^7.1.3"
    "react-router": "^7.1.3"
  web-style:
    "autoprefixer": "^10.4.20"
    "clsx": "^2.1.1"
    "postcss": "^8.5.1"
    "sass-embedded": "^1.83.4"
    "@tailwindcss/vite": "^4.0.0"
    "tailwindcss": "^4.0.0"
    "tailwind-merge": "^2.6.0"
    "tailwindcss-animate": "^1.0.7"
  web-tanstack:
    "@tanstack/react-form": "^0.41.3"
    "@tanstack/react-query": "^5.64.2"
    "@tanstack/react-query-devtools": "^5.64.2"
    "@tanstack/react-router": "^1.97.3"
    "@tanstack/react-table": "^8.20.6"
    "@tanstack/router-devtools": "^1.97.3"
    "@tanstack/router-plugin": "^1.97.3"
    "@tanstack/start": "^1.97.3"
    "@tanstack/zod-form-adapter": "^0.41.3"
  web-validation:
    "class-variance-authority": "^0.7.1"
  web-vite:
    "@vitejs/plugin-react": "^4.3.4"
    "@vitejs/plugin-react-swc": "^3.5.0"
    "vite": "^6.0.11"
    "vite-env-only": "^3.0.3"
    "vite-plugin-cjs-interop": "^2.1.6"
    "vite-plugin-esmodule": "^1.5.0"
    "vite-tsconfig-paths": "^5.1.4"