services:
  http:
    image: ${ROOT_IMAGE}
    entrypoint: project
    environment:
      PROJECT_PATH: .
      PROJECT_COMMAND: http:dev
      PORT: "${ROOT_NS}${HTTP_NS}${SPORK_NS}${SPORK_HTTP}"
      LOG_LEVEL: "${LOG_LEVEL}"
    depends_on:
      - routemap
    ports:
      - "${ROOT_NS}${HTTP_NS}${SPORK_NS}${SPORK_HTTP}:${ROOT_NS}${HTTP_NS}${SPORK_NS}${SPORK_HTTP}"