services:
  spork-http:
    image: "spork"
    entrypoint: project
    environment:
      LOG_LEVEL: "5"
      PORT: "3201"
      PROJECT_COMMAND: "http:watch"
      PROJECT_PATH: "."
      # STRUCTURED_LOGGING: "awspowertools"
    ports:
      - "3201:3201"