version: 0.2

phases:
  install:
    commands:
      - uname -ms
      - export TASK_ROOT=$(pwd)
      - apt-get -y update && apt-get -y upgrade && apt-get -y install curl
      - curl -fsSL https://bun.sh/install | bash
      - export PATH=$PATH:/root/.bun/bin
      - cd bun/ci/stacks/toolchain
      - bun install
  pre_build:
    commands:
      - curl -fsSL https://get.pulumi.com | bash
      - export PATH=$PATH:/root/.pulumi/bin
      - pulumi version
      - pulumi login --local
  build:
    commands:
      - pulumi stack init ci-builder
      - pulumi up --yes